# Setup
title: Sejin&#39;s Blog ♥
description: ☺ Seoul, Korea <br>☻ Lille, France
url: https://github.com/SejinPrk
avatar: /profile.jpeg
paginate: 5
permalink: pretty
cover_image: /IMG_2944.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - /sejinpic.jpeg

# Optimize Jekyl SEO Tag
github:
  username: SejinPrk
  card: summary
logo: logo.png
social:
  name: Sejin Park
  links:
    - https://www.instagram.com/sejinprk/
    - https://github.com/SejinPrk
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Sejin Park
  url: https://github.com/SejinPrk
  email: bestsaejin12@gmail.com
